theme: jekyll-theme-minimal
logo: "blob:https://web.whatsapp.com/22321f02-f610-4ac4-aa71-e2c07502d0d4"
title: "Amit K. Dubey"
description: "Computer Science & Engineering \nUndergrad at Ramaiah Institute of Technology"
projects: "https://amitdu6ey.github.io/#Projects"
