theme: jekyll-theme-minimal
logo: "https://drive.google.com/file/d/1dk0q3892pHNS1wAACznDaQXkXErBgjGz/view?usp=sharing"
title: "Amit Dubey"
description: "Computer Science & Engineering \nUndergrad at Ramaiah Institute of Technology"
