theme: jekyll-theme-minimal
logo: "https://storage.googleapis.com/kaggle-avatars/images/2138295-kg.jpg"
title: "Amit Dubey"
description: "Computer Science & Engineering \nUndergrad at Ramaiah Institute of Technology"
