theme: jekyll-theme-minimal
logo: "https://avatars0.githubusercontent.com/u/35802447?s=400&u=8249db5e7f7f778f57d27a70a1f4811e0cd25e35&v=4"
title: "Amit K. Dubey"
description: "Computer Science & Engineering \nUndergrad at Ramaiah Institute of Technology"
projects: "https://amitdu6ey.github.io/#Projects"
