theme: jekyll-theme-minimal
logo: "https://avatars2.githubusercontent.com/u/35802447?s=400&u=edf6c52f05258cd73a938a4093ebb634b2e01eba&v=4"
title: "Amit K. Dubey"
description: "Computer Science & Engineering \nUndergrad at Ramaiah Institute of Technology"
projects: "https://amitdu6ey.github.io/#Projects"
