theme: jekyll-theme-minimal
logo: "https://avatars1.githubusercontent.com/u/35802447?s=460&v=4"
title: "Amit K. Dubey"
description: "Computer Science & Engineering \nUndergrad at Ramaiah Institute of Technology"
projects: "https://amitdu6ey.github.io/#Projects"
