theme: jekyll-theme-minimal
logo: "https://www.instagram.com/p/B1kCHNhHSaoiZeBoIJVrrz-gpaXq38beqOPqbA0/"
title: "Amit Dubey"
description: "Computer Science & Engineering \nUndergrad at Ramaiah Institute of Technology"
