theme: jekyll-theme-minimal
title: "The title of your site"
description: "A short description of your site's purpose"
logo: "https://media.licdn.com/dms/image/C5103AQE_Rkhh1mQC8w/profile-displayphoto-shrink_200_200/0?e=1577923200&v=beta&t=WPJiNAuxWNpqwxOGcjWrcBYaioekBg6juiyqiTgBKhA"
