theme: jekyll-theme-minimal
logo: "https://www.facebook.com/photo.php?fbid=2826453817579281&set=pb.100006440711605.-2207520000.1572506221.&type=3&size=585%2C585"
title: "Amit Dubey"
description: "Computer Science & Engineering \nUndergrad at Ramaiah Institute of Technology"
