theme: jekyll-theme-minimal
title: "The title of your site"
description: "A short description of your site's purpose"
logo : "https://fsmedia.imgix.net/a9/98/c5/2b/4d80/44a8/9662/5ff9bc5406d2/tom-holland-as-spider-man-in-captain-america-civil-war.jpeg?rect=0%2C0%2C2158%2C1078&auto=format%2Ccompress&dpr=2&w=650"
