theme: jekyll-theme-minimal
logo: "https://pps.whatsapp.net/v/t61.24694-24/72887138_190988281927362_6147231244745226182_n.jpg?oe=5DC008F6&oh=ac6c34c2b3cd62e2459ed5fbad9c29d0"
title: "Amit K. Dubey"
description: "Computer Science & Engineering \nUndergrad at Ramaiah Institute of Technology"
projects: "https://amitdu6ey.github.io/#Projects"
