theme: jekyll-theme-minimal
logo: "https://avatars0.githubusercontent.com/u/35802447?s=400&u=7dae2d473fff74731ee4af027242ffe866f45e4f&v=4"
title: "Amit K. Dubey"
description: "Incoming SWE Intern @ JP Morgan Chase & Co"
